/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Main {

  public static void main(String[] args) {
      // Use this method to test your code



  }


}
